### ISSUE TITLE
Error when configure

### ISSUE THREAD

**Issue by MCredbear** [teacupx/xserver-rockchip#1]
My system is debian testing,built by debootstrap

I used the configure command that create by dpkg-buildpackages,then it reported:

checking for glproto >= 1.4.17 gl >= 9.2.0... no
configure: error: Package requirements (glproto >= 1.4.17 gl >= 9.2.0) were not met:

Requested 'gl >= 9.2.0' but version of GL is 1.2

there were two packages providing gl.pc in my system:
libgl-dev  (1.3.2-1)
libgl1-mesa-dev  (20.3.4-1)

if I edit configure and configure.ac,change "gl >= 9.2.0" to "gl >= 1.2",it can configure successfully,but,when compiling,it reports error:

/usr/include/X11/Xlib.h:222:2: error: conflicting types for ‘GC’
  222 | *GC;
      |  ^~
In file included from ../../../../glamor/glamor.h:34,
                 from ../../../../glamor/glamor_priv.h:32,
                 from ../../../../glamor/glamor_dash.c:23:
../../../../include/gcstruct.h:289:3: note: previous declaration of ‘GC’ was here
  289 | } GC;
      |   ^~
In file included from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/epoxy/egl_generated.h:11,                 from /usr/include/epoxy/egl.h:46,
                 from ../../../../glamor/glamor_priv.h:43,
                 from ../../../../glamor/glamor_font.c:23:
/usr/include/X11/Xlib.h:222:2: error: conflicting types for ‘GC’
  222 | *GC;
      |  ^~
In file included from ../../../../glamor/glamor.h:34,
                 from ../../../../glamor/glamor_priv.h:32,
                 from ../../../../glamor/glamor_font.c:23:
../../../../include/gcstruct.h:289:3: note: previous declaration of ‘GC’ was here
  289 | } GC;
      |   ^~
make[3]: *** [Makefile:763：glamor_image.lo] 错误 1
make[3]: *** 正在等待未完成的任务....

**Comment by teacupx** [comment]
Yes, that is the main reason why [I am only publishing packages for Debian Buster](https://forum.armbian.com/topic/16516-rk3399-legacy-multimedia-framework/). In newer versions (Debian Bullseye, Ubuntu Focal), you get this error. 

Solving it requires deep modifications, that need to be done upstream in Rockchip. The purpose of this repo is merely do the necessary adaptations for Armbian. If upstream Rockchip develops a stable version for newer X servers, I may think about backporting it. But it is not for sure since, as I state in the documentation linked above, our intention at Armbian is to focus on Mainline Linux kernel for future releases, and leave Buster as the last distro supporting the multimedia capabilities of the 4.4 kernel.

Therefore, I am closing this issue as "**Won't fix**". If you still want to create a package for newer distros, I suggest you report the issue in the upstream Rockchip repo.
